### ISSUE TITLE
Feature: User can create a post

### ISSUE THREAD

**Issue by arcan9** [arcan9/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a media post and add a description.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking “Add Post” in the menu brings up the form. Clicking on the plus(+) icon in the form allows user to add an image from their own local device. Below the image, user can input text for their description. The "Post" button will post the content to their feed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CREATE-A-POST-FULL](https://user-images.githubusercontent.com/102492480/200665479-52569ebe-e15f-4bfe-bfeb-5511586144c3.png)
![CREATE-A-POST-FULL-DESKTOP](https://user-images.githubusercontent.com/102492480/200665500-94aa570b-7a42-4799-9c3f-45b8837b4d8b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create database table
- [x] Update `data.sql` to insert starting data

### ☁️ Server Tasks

- [x] Update `server/index.js` to determine how it will respond to the `POST` request from the client side
- [x] Create a url for the uploaded image using `join`
- [x] Query the database with `SQL` and user input (as params).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create navbar component
- [x] Add styling to components
  - [x]  Style the create post page
  - [x] Style the home page
- [x] add hashchange event that switches the view to a form for uploading photos
- [x] Add anchors to nav bar
- [x] add handleSubmit to the form component
- [x] Prevent browser's default behavior with `event.preventDefault`
- [x] Create a `new` FormData object
- [x] Append the image file and caption to the form data object
- [x] Make a `fetch` request to save the data object to the database
  - [x] Make sure the second argument for `fetch` is a config object with the method of `POST`
- [x] Render the image to page when user posts it

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
