### ISSUE TITLE
Feature: User can edit a post

### ISSUE THREAD

**Issue by arcan9** [arcan9/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their post.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the pencil icon on their own post will bring up the entry form which will allow user to edit their post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![EDIT-A-POST-FULL](https://user-images.githubusercontent.com/102492480/200683072-bb299747-9980-4e5e-a04c-9448d2c8392e.png)
![EDIT-A-POST-FULL-DESKTOP](https://user-images.githubusercontent.com/102492480/200683085-a917c8d1-d2b2-4fba-859a-745ca94b41fd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a `PATCH` http request
- [x] add a query to the database for the relevant data rows
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to `handleEdit` when `onSubmit` event listener is fired
- [x] add `event.preventDefault()` inside edit handler
- [x] Create a new `FormData` object
- [x] Make a fetch request for `PATCH`
- [x] When user clicks on edit anchor, the url should be updated with the postId: `#editposts?postId=${post.postId}`
- [x] Inside `handleEdit` find the index of the post with the matching postId in the state array
- [x] In the `App` component `get()` route params for the `postId` of the post in the url
- [x] Add `postId` as props to posts when on edit mode
- [x] Ensure that when user updates a post, the app returns them to the homepage 
- [x] Ensure that the edited post has replaced the old one
- [x] Add `isEditing` state in the `App` component to keep track of when editing is activated
- [x] Pass `isEditing` state as props to components that need it

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
